# Generated by Django 3.2.10 on 2021-12-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('EmployeeFirstName', models.CharField(max_length=100)),
                ('EmployeeLastName', models.CharField(max_length=100)),
                ('EmployeeDesignation', models.CharField(max_length=100)),
                ('EmployeeAddress', models.CharField(max_length=200)),
                ('EmployeePhoneNumber', models.CharField(max_length=15)),
                ('EmployeeEmail', models.EmailField(max_length=100)),
                ('EmployeePin', models.CharField(max_length=100)),
                ('EmployeeRole', models.CharField(max_length=100)),
            ],
        ),
    ]
