# Generated by Django 3.2.10 on 2021-12-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeId', models.PositiveBigIntegerField()),
                ('SuiteNumber', models.IntegerField()),
                ('AccessDate', models.DateField(auto_now_add=True)),
                ('AccessTime', models.TimeField(auto_now_add=True)),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
    ]
